version: '3.9'
services:
  mydb:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: omri
      POSTGRES_PASSWORD: omri
      POSTGRES_DB: graphql-demo
#  adminer:

#    image: adminer:latest
#    restart: always
#    ports:
#      - 8081:8080
volumes:
  db-data: