## default connection pool
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximum-pool-size: 5
    ## PostgreSQL
#    url: jdbc:postgresql://localhost:54321/graphql-demo
#    username: omri
#    password: omri
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    #drop n create a table again, good for testing, comment this in production
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
