## default connection pool
spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    ## H2 DB
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=ID
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      globally_quoted_identifiers: true
    show-sql: false
#    generate-ddl: true
    #drop n create a table again, good for testing, comment this in production
    hibernate:
      ddl-auto: create-drop
